### ISSUE TITLE
Test crashes on i686 with mpich

### ISSUE THREAD

**Issue by opoplawski** [Unidata/netcdf-fortran#397]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
* a description of the issue with the steps needed to reproduce it

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

Building netcdf-fortran 4.5.4 and 4.6.0 on Fedora with:
```
mpich-4.0.3-1.fc39
gcc-13.0.1-0.10.fc39
```
we see the following failure on i686:
```
FAIL: run_f90_par_test.sh
=========================

Testing netCDF parallel I/O through the F90 API.
  
 *** Testing netCDF-4 parallel I/O from Fortran 90.
 *** SUCCESS!
  
 *** Testing netCDF-4 parallel I/O with strided access.
 *** SUCCESS!
  
 *** Testing netCDF-4 parallel I/O with fill values.
 *** SUCCESS!
           0           1           1           1           3           1           1   1.00000000       2.00000000       3.00000000    
           7           4           4           1           3           1           1   22.0000000       23.0000000       24.0000000    
           1           4           1           1           3           1           1   4.00000000       5.00000000       6.00000000    
           4           1           3           1           3           1           1   13.0000000       14.0000000       15.0000000    
           5           4           3           1           3           1           1   16.0000000       17.0000000       18.0000000    
           2           1           2           1           3           1           1   7.00000000       8.00000000       9.00000000    
           6           1           4           1           3           1           1   19.0000000       20.0000000       21.0000000    
           3           4           2           1           3           1           1   10.0000000       11.0000000       12.0000000    
 *** Testing fill values with parallel I/O.
 *** SUCCESS!
 *** Testing compressed data writes with parallel I/O.
munmap_chunk(): invalid pointer
Fatal glibc error: malloc.c:2593 (sysmalloc): assertion failed: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)

Program received signal SIGABRT: Process abort signal.
Fatal glibc error: malloc.c:2593 (sysmalloc): assertion failed: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:

Backtrace for this error:

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0xf7a192f5 in ???
#1  0xf7a1840d in ???
#2  0xf7f3559f in ???
#3  0xf7f35589 in ???
#4  0xf7876466 in ???
#5  0xf78222a4 in ???
#6  0xf780a36f in ???
#7  0xf780b2d8 in ???
#8  0xf781a3f6 in ???
#9  0xf7884769 in ???
#10  0xf7885583 in ???
#11  0xf788614e in ???
#0  0xf7a192f5 in ???
#1  0xf7a1840d in ???
#2  0xf7f6459f in ???
#3  0xf7f64589 in ???
#4  0xf789f466 in ???
#5  0xf784b2a4 in ???
#6  0xf783336f in ???
#7  0xf78342d8 in ???
#8  0xf78aab6c in ???
#9  0xf78aae7a in ???
#10  0xf78af37c in ???
#12  0xf70a2195 in ???
#13  0xf6d4a6ec in ???
#14  0xf6d4b000 in ???
#11  0xf7218e08 in ???
#15  0xf6ad4e11 in ???
#12  0xf7185b63 in ???
#16  0xf6d1c75b in ???
#17  0xf6cffda5 in ???
#18  0xf6d08b20 in ???
#19  0xf6ad2dc9 in ???
#20  0xf767a955 in ???
#21  0xf767ad71 in ???
#22  0xf762188e in ???
#13  0xf711cc43 in ???
#14  0xf717743d in ???
#15  0xf7177551 in ???
#16  0xf702341d in ???
#17  0xf6d49763 in ???
#18  0xf6d4b000 in ???
#19  0xf6ad4e11 in ???
#20  0xf6d1c75b in ???
#21  0xf6cffda5 in ???
#22  0xf6d08b20 in ???
#23  0xf6ad2dc9 in ???
#24  0xf76a3955 in ???
#25  0xf76a3d71 in ???
#26  0xf764a88e in ???
#23  0xf7e94ffd in nf_put_vara_real_
        at ../../fortran/nf_varaio.F90:372
#27  0xf7ec3ffd in nf_put_vara_real_
        at ../../fortran/nf_varaio.F90:372
#24  0xf7ef4725 in __netcdf_MOD_nf90_put_var_4d_fourbytereal
        at ../../fortran/netcdf_expanded.F90:1035
#28  0xf7f23725 in __netcdf_MOD_nf90_put_var_4d_fourbytereal
        at ../../fortran/netcdf_expanded.F90:1035
#25  0x565ed8ed in f90tst_parallel_compressed
        at ../../nf03_test4/f90tst_parallel_compressed.F90:261
#26  0x565eb5c2 in main
        at ../../nf03_test4/f90tst_parallel_compressed.F90:16
#29  0x565aa8ed in f90tst_parallel_compressed
        at ../../nf03_test4/f90tst_parallel_compressed.F90:261
#30  0x565a85c2 in main
        at ../../nf03_test4/f90tst_parallel_compressed.F90:16
#0  0xf7a192f5 in ???
#1  0xf7a1840d in ???
#2  0xf7f3459f in ???
#3  0xf7f34589 in ???
#4  0xf7876466 in ???
#5  0xf78222a4 in ???
#6  0xf780a36f in ???
#7  0xf780b2d8 in ???
#8  0xf781a3f6 in ???
#9  0xf7884769 in ???
#10  0xf7885583 in ???
#11  0xf788614e in ???
#12  0xf6b9d9b5 in ???
#13  0xf6d4a63d in ???
#14  0xf6d4b000 in ???
#15  0xf6ad4e11 in ???
#16  0xf6d1c75b in ???
#17  0xf6cffda5 in ???
#18  0xf6d08b20 in ???
#19  0xf6ad2dc9 in ???
#20  0xf767a955 in ???
#21  0xf767ad71 in ???
#22  0xf762188e in ???
#23  0xf7e93ffd in nf_put_vara_real_
        at ../../fortran/nf_varaio.F90:372
#24  0xf7ef3725 in __netcdf_MOD_nf90_put_var_4d_fourbytereal
        at ../../fortran/netcdf_expanded.F90:1035
#25  0x565f58ed in f90tst_parallel_compressed
        at ../../nf03_test4/f90tst_parallel_compressed.F90:261
#26  0x565f35c2 in main
        at ../../nf03_test4/f90tst_parallel_compressed.F90:16

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 59003 RUNNING AT f32bc652ea574bef9471ec7e57bde6e8
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Terminated (signal 15)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
FAIL run_f90_par_test.sh (exit status: 143)
```

**Comment by WardF** [comment]
Good to know; 32-bit builds/tests are still important to us, although they are becoming less easy to test without maintaining physical i686 hardware.  I'll take a look!
